version: '3.7'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'user_db'
      MYSQL_USER: '${user}'
      MYSQL_PASSWORD: '${password}'
      MYSQL_ROOT_PASSWORD: '${root_password}'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      #3306
      - '${port_exposed}:${port_exposed}'
    expose:
      # Opens port 3306 on the container
      - '${port_exposed}'
    # running the startup sql script. This path is within the container.
    volumes:
      #from hostmachine directory:to container directory
      - user_db:/var/lib/mysql
      #mounting this machines startup scripts. Will execute in alphabetical order.
      - ./startupScripts:/docker-entrypoint-initdb.d
      - ./mountInContainer:/helper

# Names our volume
volumes:
  user_db:
